### ISSUE TITLE
Pretrained word2vec missing

### ISSUE THREAD

**Issue by natny** [wboag/awecm#1]
Could you please confirm if it is available?

**Comment by wboag** [comment]
Interesting, the link has changed. It used to be

https://drive.google.com/file/d/0B7XkCwpI5KDY

but now the new link is

https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing

I will edit the readme accordingly.

**Comment by natny** [comment]
that was quick! Thanks!

**Comment by natny** [comment]
Hello again, I have been trying to run your algorithm on data from mimic and when in the word2vecf stage, my 32G memory seems insufficient. How much did you use?
